### ISSUE TITLE
Unsupported BMP compression (%d)" % file_info['compression']

### ISSUE THREAD

**Issue by ghost** [allexpy/image-converter#1]
Hi,

I tried to use your code with a .bmp image and i have ended up with the below error log. It would be grateful if you help me in sorting the error or guide me to go through it.

> 
> ```
> Traceback (most recent call last):
>   File "D:/widowed_hulk/otokar/image_converter.py", line 73, in <module>
>     processImage()
>   File "D:/widowed_hulk/otokar/image_converter.py", line 42, in processImage
>     img = Image.open(path_originals+infile)
>   File "C:\Python34\lib\site-packages\PIL\Image.py", line 2609, in open
>     im = _open_core(fp, filename, prefix)
>   File "C:\Python34\lib\site-packages\PIL\Image.py", line 2599, in _open_core
>     im = factory(fp, filename)
>   File "C:\Python34\lib\site-packages\PIL\ImageFile.py", line 102, in __init__
>     self._open()
>   File "C:\Python34\lib\site-packages\PIL\BmpImagePlugin.py", line 201, in _open
>     self._bitmap(offset=offset)
>   File "C:\Python34\lib\site-packages\PIL\BmpImagePlugin.py", line 161, in _bitmap
>     raise IOError("Unsupported BMP compression (%d)" % file_info['compression'])
> OSError: Unsupported BMP compression (1)
> ```
I am using Python 3.4.4 in Windows 7 Professional Machine. 

Thanks in advance.

**Comment by Dreyk007** [comment]
Looks like something wrong with your images...
